### ISSUE TITLE
How to use predict.py

### ISSUE THREAD

**Issue by daffigusti** [JanPalasek/ulozto-captcha-breaker#16]
Hello, 

I've generate my own training model.

But Get error when try to run with predict.py.

`python bin/predict.py  --available_chars=abcdefghijklmnopqrstuvwxyz1234567890 --image_path='out/data/22c7g7_b081c975-f657-4e32-872a-d879717ca983.png' --model_path=out/model.tflite `

`
Traceback (most recent call last):
  File "/Users/daffigusti/development/mutasibank_bot/ulozto-captcha-breaker/bin/predict.py", line 37, in <module>
    main(args)
  File "/Users/daffigusti/development/mutasibank_bot/ulozto-captcha-breaker/bin/predict.py", line 20, in main
    model : tf_keras.Model = tf_keras.models.load_model(args.model_path)
  File "/Users/daffigusti/development/mutasibank_bot/ulozto-captcha-breaker/venv/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/daffigusti/development/mutasibank_bot/ulozto-captcha-breaker/venv/lib/python3.9/site-packages/h5py/_hl/files.py", line 533, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/Users/daffigusti/development/mutasibank_bot/ulozto-captcha-breaker/venv/lib/python3.9/site-packages/h5py/_hl/files.py", line 226, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
OSError: Unable to open file (file signature not found)`

Plz help with this error.

Thanks.

**Comment by JanPalasek** [comment]
Hey, it wasn't implemented previously. It should be fixed now in the master.
